
<script type="text/javascript" src="/public/js/financeiro/caixas.js"></script>

<div id="finan_lanc_janela" class="janela col-lg-push-4 col-lg-2" style="display: none" data-title="FinanCaixas">
    <div class="divisao-janela">
        <form id="finan_lanc_modal_caixas_form">
                <div class="modal-header">
                    <button type="button" data-toggle="tooltip" data-placement="bottom" title="Fechar">
                        <i class="fa fa-close "></i>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-edit "></i> Caixas</h4>
                </div>
                <div class="modal-body clearfix">

                    <div id="finan_lanc_modal_caixas_alertas" class="label label-default col-lg-12 hide"></div>

                    <div class="form-group col-lg-12">
                        <label>Caixas *</label>
                        <select class="form-control" name="id" id="finan_lanc_modal_caixas_id">
                            <option value="0">Novo...</option>
                        </select>
                    </div>

                    <div class="form-group col-lg-12">
                        <label>Nome *</label>
                        <input class="form-control col-lg-12" name="nome" id="finan_lanc_modal_caixas_nome" required />
                    </div>

                    <div class="col-lg-12 text-right" >
                        <input type="checkbox" name="epadrao" id="finan_lanc_modal_caixas_epadrao" /> Padrão
                    </div>
                    
                    <div class="col-lg-12 text-right" style="left:-13px">
                        <input type="checkbox" name="status" id="finan_lanc_modal_caixas_status" checked /> Ativa
                    </div>

                    <div class="col-lg-12 text-center" >
                        <button class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                            <i class="fa fa-check" style="color:#cc7a00"></i>
                        </button>
                    </div>

                </div>
            </form>
    </div>
</div>