
<script type="text/javascript" src="/public/js/financeiro/categorias.js"></script>

<div id="finan_janela" class="janela col-lg-push-4 col-lg-3" style="display: none" data-title="FinanCategorias">
    <div class="divisao-janela">
        <form id="finan_catfilho_form">
                <div class="modal-header">
                    <button type="button" data-toggle="tooltip" data-placement="bottom" title="Fechar">
                        <i class="fa fa-close "></i>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-edit "></i> Categorias</h4>
                </div>
                <div class="modal-body clearfix">

                    <div id="finan_catfilho_alertas" class="label label-default col-lg-12 hide"></div>

                    <div class="form-group col-lg-12">
                        <label>Categoria *</label>
                        <select class="form-control" name="id" id="finan_catfilho_id">
                            <option value="0">Nova...</option>
                        </select>
                    </div>

                    <div class="form-group col-lg-10">
                        <label>Categoria Pai*</label>
                        <select class="form-control" name="categorias_id" id="finan_catpai"></select>
                    </div>

                    <div class="form-group col-lg-2">
                        <a href="#" id="finan_catpai_edit" class="text-center btn btn-default" data-toggle="tooltip" style="margin-top: 20px">
                            <i class="fa fa-edit" style="color:#cc7a00"></i>
                        </a>
                    </div>

                    <div class="form-group col-lg-12">
                        <label>Nome *</label>
                        <input class="form-control col-lg-12" name="nome" id="finan_catfilho_nome" required />
                    </div>

                    <div class="col-lg-2" style="float: right">
                        <input type="checkbox" name="status" id="finan_catfilho_status" checked /> Ativa
                    </div>

                    <div class="col-lg-12 text-center" >
                        <button class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                            <i class="fa fa-check" style="color:#cc7a00"></i>
                        </button>
                    </div>

                </div>
            </form>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="finan_catpai_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form id="finan_catpai_form">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close "></i></button>
                    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-edit "></i> Gerenciar categorias-pai</h4>
                </div>
                <div class="modal-body clearfix">

                    <div id="finan_catpai_alertas" class="label label-default col-lg-12 hide"></div>

                    <div class="form-group col-lg-12">
                        <label>Categoria-Pai *</label>
                        <select class="form-control" name="id" id="finan_catpai_id">
                            <option value="0">Nova...</option>
                        </select>
                    </div>

                    <div class="form-group col-lg-12">
                        <label>Nome *</label>
                        <input class="form-control col-lg-12" name="nome" id="finan_catpai_nome" required />
                    </div>

                    <div class="col-lg-3" style="float: right">
                        <input type="checkbox" name="status" id="finan_catpai_status" checked /> Ativa
                    </div>

                    <div class="col-lg-12 text-center" >
                        <button class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                            <i class="fa fa-check" style="color:#cc7a00"></i>
                        </button>
                    </div>
                    
                </div>
                <div class="modal-footer">
                    <button class="text-center" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                        <i class="fa fa-check "></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>