
<script type="text/javascript" src="/public/js/financeiro/lancamentos.js"></script>

<style>
    .modal-lg {
        width: 1300px;
    }

    .table button, .table button:hover {
        background: transparent;
        padding: 0;
        font-size: 14px;
    }
</style>

<div id="finan_lanc_janela" class="janela col-lg-push-3 col-lg-4" style="display: none" data-title="FinanLanc">
    <div class="divisao-janela">
        <div class="modal-header">
            <button type="button" data-toggle="tooltip" data-placement="bottom" title="Fechar">
                <i class="fa fa-close "></i>
            </button>
            <h4 class="modal-title"><i class="fa fa-money"></i> Lançamentos </h4>
        </div>
        <div class="modal-body clearfix" style="padding-bottom: 5px;">

            <div id="finan_lanc_alertas" class="label label-default col-lg-12 hide"></div>

            <div class="form-group col-lg-12" style="margin: 10px 0">
                <button type="button" class="btn btn-default btn-sm" id="finan_lanc_ultlanc_btn"><i class="fa fa-list-ol fa-1x"></i></button>
            </div>

            <form class="col-lg-12 clear-both" method="POST" id="finan_lanc_form">
                <div>
                    <div class="form-group col-lg-6">
                        <label>Caixa *</label>
                        <select class="form-control" name="caixa_id" id="finan_lanc_caixas"></select>
                    </div>
                    <div class="form-group col-lg-6">
                        <label>Categoria *</label>
                        <select class="form-control" name="categoria_id" id="finan_lanc_cat"></select>
                    </div>
                </div>


                <div class="">
                    <div class="form-group col-lg-8">
                        <label>Descrição *</label>
                        <input type="text" class="form-control" name="descricao" id="finan_lanc_descricao" required />
                    </div>

                    <div class="form-group col-lg-4" id="finan_lanc_tipo">
                        <label>Tipo de lançamento *</label><br>
                        <input type="radio" value="D" name="tipo" checked /> Despesa
                        <input type="radio" value="R" name="tipo" /> Receita
                    </div>

                </div>

                <div class="form-group col-lg-9" id="finan_lanc_formapagto" style="margin: 20px 0">
                    <label>Tipo Pagamento</label><br />
                    <input type="radio" value="AV" name="formapagto" checked /> A Vista
                    <input type="radio" value="CH" name="formapagto" /> Cheque
                    <input type="radio" value="BOL" name="formapagto" /> Boleto
                    <input type="radio" value="CAR" name="formapagto" /> Cartão
                </div>

                <div class="col-lg-12" id="finan_lanc_todasparcelas">
                    <label>Parcelas *</label><br>

                    <div class="col-lg-12">
                        <button type="button" class="btn btn-default btn-sm" id="finan_lanc_addparcela"><i class="fa fa-plus"></i></button>
                        <button type="button" class="btn btn-default btn-sm" id="finan_lanc_remparcela"><i class="fa fa-minus"></i></button>
                    </div>

                    <div class="col-lg-12" id="finan_lanc_parcela1">
                        <div class="form-group col-lg-3">
                            <label>Data</label>
                            <input class="form-control" name="parcelas[1][dtavencimento]" id="finan_lanc_dtavencimento1" readonly />
                        </div>

                        <div class="form-group col-lg-3">
                            <label>Valor</label>
                            <input class="form-control" name="parcelas[1][valor]" id="finan_lanc_valor1" data-mask="money" required />
                        </div>
                        <div class="form-group col-lg-2">
                            <label>Situação</label> <br />
                            <input type="checkbox" name="parcelas[1][situacao]" value="P" id="finan_lanc_situacao1" /> Pago
                        </div>

                        <div id="finan_lanc_pagamento1" class="col-lg-3 finan_lanc_dtapagamento1 hide" style="margin-left: -20px">
                            <div class="form-group">
                                <label class="col-lg-12">Data: </label>
                                <input class="form-control" name="parcelas[1][dtapagamento]" id="finan_lanc_dtapagamento1" readonly />
                            </div>
                        </div>
                        <input type="hidden" name="parcelas[1][id]" id="finan_lanc_id1" />
                    </div>

                </div>

                <input type="hidden" name="id" id="finan_lanc_id" />

                <div class="col-lg-12 text-center" style="margin-top: 20px" >
                    <button class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                        <i class="fa fa-check" style="color:#cc7a00"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="finan_lanc_ultlanc" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close "></i></button>
                <h4 class="modal-title" id="myModalLabel"><i class="fa fa-edit "></i> Últimos lançamentos</h4>
            </div>
            <div class="modal-body clearfix">

                <div id="finan_lanc_ultlanc_alertas" class="label label-default col-lg-12"></div>

                <div id="finan_lanc_ultlanc" class="col-lg-12" style="margin-top: 10px">
                    <table class="table table-bordered table-condensed table-striped" id="finan_lanc_tab_ultlanc">
                        <thead>
                            <tr>
                                <th class="col-lg-1">#</th>
                                <th>Descrição</th>
                                <th class="col-lg-1">Editar</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
