<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'href' => ''))
        ->prependStylesheet($this->basePath() . 'public/css/index.css');

echo $this->headScript()
        ->prependFile($this->basePath() . 'public/js/index.js');

$this->headMeta()->appendName('keywords', 'Sistema, Agendas');
?>
<!-- Cabeçalho -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">

    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div style="color: #FF9900; margin-top: 7px" ><img src="<?= $this->basePath() . 'public/img/id-visual/logo_36.png' ?>" /></div>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav col-lg-push-3" style="position: relative">
                
                <li>
                    <div class="dropdown">
                        <button type="button" class="btn btn-app-dropdown" data-toggle="dropdown" data-placement="right"><i class="fa fa-money fa-1x" aria-hidden="true"></i><br /><span>Financeiro</span><span class="caret"> </span></button>
                        <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li class="open-app" data-title="FinanLanc" title="FinanLanc"><a href="#"><i class="fa fa-money fa-1x" aria-hidden="true"></i><span> Lançamentos</span></a></li>
                            <li class="open-app" data-title="FinanDet" title="FinanDet"><a href="#"><i class="fa fa-money fa-1x" aria-hidden="true"></i><span> Detalhamento</span></a></li>
                            <li class="open-app" data-title="FinanCategorias" title="FinanCategorias"><a href="#"><i class="fa fa-money fa-1x" aria-hidden="true"></i><span> Categorias</span></a></li>
                        </ul>
                    </div>
                </li>
                
                <li> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="ManutLanc" title="ManutLanc"><i class="fa fa-wrench fa-1x" aria-hidden="true"></i><br /><span>Manutenção</span></button> </li>
                
                <li>
                    <div class="dropdown">
                        <button type="button" class="btn btn-app-dropdown" data-toggle="dropdown" data-placement="right" data-title="Produtos" title="Produtos"><i class="fa fa-shopping-cart fa-1x" aria-hidden="true"></i><br /><span>Produtos</span><span class="caret"> </span></button>
                        <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li class="open-app" data-title="ProdLanc" title="ProdLanc"><a href="#"><i class="fa fa-shopping-cart fa-1x" aria-hidden="true"></i><span> Lançamentos</span></a></li>
                            <li class="open-app" data-title="ProdEst" title="ProdEst"><a href="#"><i class="fa fa-shopping-cart fa-1x" aria-hidden="true"></i><span> Estoque</span></a></li>
                            <li class="open-app" data-title="ProdMarcas" title="ProdMarcas"><a href="#"><i class="fa fa-shopping-cart fa-1x" aria-hidden="true"></i><span> Marcas</span></a></li>
                            <li class="open-app" data-title="ProdCategorias" title="ProdCategorias"><a href="#"><i class="fa fa-shopping-cart fa-1x" aria-hidden="true"></i><span> Categorias</span></a></li>
                        </ul>
                    </div>
                </li>
                
                <li>
                    <div class="dropdown">
                        <button type="button" class="btn btn-app-dropdown" data-toggle="dropdown" data-placement="right"><i class="fa fa-user fa-1x" aria-hidden="true"></i><br /><span>Pessoas</span><span class="caret"> </span></button>
                        <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li class="open-app" data-title="Pessoas" title="Pessoas"><a href="#"><i class="fa fa-user fa-1x" aria-hidden="true"></i><span> Pessoas</span></a></li>
                            <li class="open-app" data-title="Funcionarios" title="Funcionários"><a href="#"><i class="fa fa-user fa-1x" aria-hidden="true"></i><span> Funcionários</span></a></li>
                        </ul>
                    </div>
                </li>
                
                <li> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="Veiculos" title="Veiculos"><i class="fa fa-car fa-1x" aria-hidden="true"></i><br /><span>Veículos</span></button> </li>
                
                <!--<li> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="ProdutosMarcas" title="Marcas"><i class="fa fa-shopping-cart fa-1x" aria-hidden="true"></i><br /><span>Marcas de produtos</span></button> </li>-->
                <li style="border-left: 1px solid #FF9900"> <button type="button" class="btn btn-app"><a href="/user/logout"><i class="fa fa-sign-out fa-1x" aria-hidden="true"></i><br /><span>Sair</span></a> </button></li>
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<!-- // Cabeçalho -->

<div style="padding-top:51px; height: 100%" class="container-fluid no-padding">

    <!-- Corpo -->
    <?php echo $this->partial('telas/pessoas', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/funcionarios', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/veiculos', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/prod/lancamentos', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/prod/estoque', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/prod/marcas', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/prod/categorias', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/manutencao/lancamentos', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/financeiro/lancamentos', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/financeiro/categorias', ['variaveis' => $this->telas]) ?>
    <?php echo $this->partial('telas/financeiro/detalhamentos', ['variaveis' => $this->telas]) ?>

</div>
