<?php 
    
    $base_teste_ativada = 0;
    
    echo $this->doctype(); 
    $this->plugin('basePath')->setBasePath('/public/');
?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(' Diesel ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/id-visual/logo_36.png'))
                        ->prependStylesheet($this->basePath('css/aplicacao.css'))
//                        ->prependStylesheet($this->basePath('css/global.css'))
                        ->prependStylesheet($this->basePath('vendor/bootstrap/3.3.7/css/bootstrap.min.css')) 
                        ->prependStylesheet($this->basePath('vendor/font-awesome/4.7/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('vendor/jquery-ui/1.11.4/jquery-ui.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/global/janelas.js'))
            ->prependFile($this->basePath('js/global/global.js'))
            ->prependFile($this->basePath('js/global/plugin.table.js'))
            ->prependFile($this->basePath('js/global/plugin.form.js'))
            ->prependFile($this->basePath('js/global/plugin.date.js'))
            ->prependFile($this->basePath('js/global/global.components.plugin.js'))
            ->prependFile($this->basePath('vendor/outros/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('vendor/outros/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('vendor/jquery-validation/dist/jquery.validate.min.js'))
            ->prependFile($this->basePath('vendor/outros/js/filter_input.js'))
            ->prependFile($this->basePath('vendor/outros/js/jquery.form.min.js'))
            ->prependFile($this->basePath('vendor/jquery-maskplugin/dist/jquery.mask.min.js'))
            ->prependFile($this->basePath('vendor/jquery-ui/datepicker-pt-BR.js'))
            ->prependFile($this->basePath('vendor/jquery-ui/1.11.4/jquery-ui.min.js'))
            ->prependFile($this->basePath('vendor/bootstrap/3.3.7/js/bootstrap.min.js'))
            ->prependFile($this->basePath('vendor/jquery/2.2.3.min.js'))
        ; ?>

    </head>
    <body>
        
        
        <?php if($base_teste_ativada): ?>
        <div class="container-fluid col-lg-12 text-center" style="top:300px; background: black">
            <div style="color: orange; font-size: 50px"> TL Diesel </div>
            <div style="color: orange; font-size: 25px"> Base teste inativada, acesse: tldiesel.com.br </div>
        </div>
        <?php else: ?>
        
        <div style="height: 100%">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        
        <?php endif; ?>
    </body>
</html>
