<?php

    $lancamentos = $this->result['lancamentos'];
    $resumo = $this->result['resumo'];
    $dados = $this->dados;

?>
<style>
    
    @page  
    { 
        size: auto;   /* auto is the initial value */ 
        /* this affects the margin in the printer settings */ 
        margin: 8.5mm 16mm 10mm 3mm; 
    } 

    
    body{
        background: transparent;
        text-transform: uppercase;
        -webkit-print-color-adjust:exact;
        margin: 0px;
    }
    .bold { font-weight: bold; }
    .border {
        border: 1px solid #676060;
        margin: 1px;
        padding: 2px;
    }
    .lowercase { text-transform: lowercase; }
    .capitalize { text-transform: capitalize; }

    /* BOOTSTRAP - INICIO */
    
    *:before, *:after {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }
    * {
        font-family: 'Roboto', sans-serif;
        font-size: small;
        box-sizing: border-box;
    }
    .text-center { text-align: center }
    .text-right { text-align: right; }
    .text-left { text-align: left; }
    
    .col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12
    { position: relative; min-height: 1px; padding-left: 5px; padding-right: 5px; }
    .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12{ float: left; }
    .col-lg-1 { width: 8.33333333%; }
    .col-lg-2 { width: 16.66666667%; }
    .col-lg-3 { width: 25%; }
    .col-lg-4 { width: 33.33333333%; }
    .col-lg-5 { width: 41.66666667%; }
    .col-lg-6 { width: 50%; }
    .col-lg-8 { width: 66.66666667%; }
    .col-lg-9 { width: 75%; }
    .col-lg-12 { width: 100%; }
    table {
        border-collapse: collapse;
        border-spacing: 0;
    }
    .table {
        background: white;
        width: 100%;
        max-width: 100%;
        margin-bottom: 7px;
    }
    .table-bordered { border: 1px solid #ddd; }
 
    td, th {
        padding: 0;
    }
    th {
        text-align: center;
    }
    .table>thead>tr>th, .table>tbody>tr>th, .table>tfoot>tr>th, .table>thead>tr>td, .table>tbody>tr>td, .table>tfoot>tr>td {
        padding: 8px;
        line-height: 1.2;
        vertical-align: top;
        border-top: 1px solid #ddd;
    }
    .table>thead>tr>th {
        vertical-align: bottom;
        border-bottom: 2px solid #ddd;
    }
    .table-condensed>thead>tr>th, .table-condensed>tbody>tr>th, .table-condensed>tfoot>tr>th, .table-condensed>thead>tr>td, .table-condensed>tbody>tr>td, .table-condensed>tfoot>tr>td {
        padding: 2px;
    }
    .table-bordered>thead>tr>th, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>tbody>tr>td, .table-bordered>tfoot>tr>td {
        border: 1px solid #ddd;
    }
    .table-bordered>thead>tr>th, .table-bordered>thead>tr>td {
        border-bottom-width: 2px;
    }
    .table>caption+thead>tr:first-child>th, .table>colgroup+thead>tr:first-child>th, .table>thead:first-child>tr:first-child>th, .table>caption+thead>tr:first-child>td, .table>colgroup+thead>tr:first-child>td, .table>thead:first-child>tr:first-child>td {
        border-top: 0;
    }
    .table-striped>tbody>tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }
    .table-bordered>thead>tr>th, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>tbody>tr>td, .table-bordered>tfoot>tr>td {
        border: 1px solid #ddd;
    }
    .table tbody td {
        text-align: center;
        padding: 0;
        font-size: 8px;
    }
    .table thead th {
        font-size: 8px;
    }

    /* BOOTSTRAP - FIM */
    
</style>

<div class="col-lg-12" id="os-main">

    <div class="col-lg-12 text-center bold border"> 
        <div class="col-lg-12" style="font-size: 11px">DOCUMENTO NÃO-FISCAL</div>
    </div>
    
    <div class="col-lg-12 border">
        <div class="col-lg-1 bold">Período: </div><div><?= implode('/', array_reverse(explode('-', $dados['inicio']))) ?> - <?= implode('/', array_reverse(explode('-', $dados['fim']))) ?></div>
        <div class="col-lg-1 bold">Categoria: </div><div><?= $dados['categoria_nome'] ?></div>
        <div class="col-lg-1 bold">Busca: </div><div><?= $dados['string'] ?></div>
    </div>
    
    
    <div class="col-lg-12 border">
        <div class="col-lg-4">
            <table class="table table-bordered table-condensed table-striped" style="margin: 7px 0"> 
                <thead>
                    <tr>
                        <th colspan="2" >Receitas</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>a receber</td>
                        <td>R$ <?= $resumo['receita_receber'] ?></td>
                    </tr>
                    <tr>
                        <td>caixa</td>
                        <td>R$ <?= $resumo['receita_caixa'] ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <div class="col-lg-4">
            <table class="table table-bordered table-condensed table-striped" style="margin: 7px">
                <thead>
                    <tr>
                        <th colspan="2" >Despesas</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>a pagar</td>
                        <td>R$ <?= $resumo['despesa_pagar'] ?></td>
                    </tr>
                    <tr>
                        <td>paga</td>
                        <td>R$ <?= $resumo['despesa_paga'] ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <div class="col-lg-4">
            <table class="table table-bordered table-condensed table-striped" style="margin: 7px">
                <thead>
                    <tr>
                        <th colspan="2" >Resumo</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Caixa</td>
                        <td>R$ <?= $resumo['caixa_total'] ?></td>
                    </tr>
                    <tr>
                        <td>Dízimo</td>
                        <td>R$ <?= $resumo['dizimo'] ?></td>
                    </tr>
                </tbody>
            </table>
        </div>

    </div>
    
    <div class="col-lg-12" style="margin-top: 10px">
        <div class="col-lg-6">
            <table class="table table-bordered table-condensed table-striped" id="table-rec-principal">
                <thead>
                    <tr>
                        <th colspan="6" >Receitas</th>
                    </tr>
                    <tr>
                        <th>Descrição</th> 
                        <th style="width: 15%">Valor</th> 
                        <th style="width: 2%">Categoria</th> 
                        <th style="width: 1%">Sit</th> 
                        <th style="width: 2%">Vencimento</th> 
                        <th style="width: 2%">Pagamento</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($lancamentos as $item) : if ($item['tipo']=='R'):  ?>
                    <tr style="background-color: <?=($item['situacao'])=='P'?'#deffde':'#ffeaea'?> ">
                        <td><?= $item['descricao'] ?></td>
                        <td style="width: 15%">R$ <?= $item['valor'] ?></td>
                        <td style="width: 2%"><?= $item['categoria_nome'] ?></td>
                        <td style="width: 1%"><?= $item['situacao'] ?></td>
                        <td style="width: 2%"><?= implode('/', array_reverse(explode('-', $item['dtavencimento'])))  ?></td>
                        <td style="width: 2%"><?= implode('/', array_reverse(explode('-', $item['dtapagamento'])))  ?></td>
                    </tr>
                    <?php endif; endforeach; ?>
                </tbody>
            </table>
            
        </div>
        
        <div class="col-lg-6">
            <table class="table table-bordered table-condensed table-striped" id="table-des-principal">
                <thead>
                    <tr>
                        <th colspan="6" >Despesas</th>
                    </tr>
                    <tr>
                        <th>Descrição</th> 
                        <th style="width: 15%">Valor</th> 
                        <th style="width: 2%">Categoria</th> 
                        <th style="width: 1%">Sit</th> 
                        <th style="width: 2%">Vencimento</th> 
                        <th style="width: 2%">Pagamento</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($lancamentos as $item) : if ($item['tipo']=='D'):  ?>
                    <tr style="background-color: <?=($item['situacao'])=='P'?'#deffde':'#ffeaea'?> ">
                        <td><?= $item['descricao'] ?></td>
                        <td style="width: 15%">R$ <?= $item['valor'] ?></td>
                        <td style="width: 2%"><?= $item['categoria_nome'] ?></td>
                        <td style="width: 1%"><?= $item['situacao'] ?></td>
                        <td style="width: 2%"><?= implode('/', array_reverse(explode('-', $item['dtavencimento'])))  ?></td>
                        <td style="width: 2%"><?= implode('/', array_reverse(explode('-', $item['dtapagamento'])))  ?></td>
                    </tr>
                    <?php endif; endforeach; ?>
                </tbody>
            </table>
            
        </div>

        
    </div>
    
    
</div>

<script>
//    $(function (){
//        var rec_tr_qtd = $('#table-rec-principal tbody tr').length;
//        var des_tr_qtd = $('#table-rec-principal tbody tr').length;
//        console.log(rec_tr_qtd);
//        console.log(des_tr_qtd);
//        if(rec_tr_qtd>85 || des_tr_qtd>85){ $('style').append('@media print { .page-break {page-break-after: always;} }'); }
//        
//    });
        print();
</script>
