

<script type="text/javascript" src="/public/js/produtos/categorias.js"></script>

<div id="prod_cat_janela" class="janela col-lg-push-4 col-lg-3" style="display: none" data-title="ProdCategorias">
    <div class="divisao-janela">
        <form method="POST" action="" id="prod_cat_form">
            <div class="modal-header">
                <button type="button" data-toggle="tooltip" data-placement="bottom" title="Fechar">
                    <i class="fa fa-close "></i>
                </button>
                <h4 class="modal-title"><i class="fa fa-shopping-cart "></i> Categorias de Produtos</h4>
            </div>
            <div class="modal-body clearfix" style="padding-bottom: 5px;">
                
                <div id="prod_cat_alertas" class="label label-default col-lg-12 hide"></div>

                <div class="col-lg-12">
                
                    <fieldset>
                        <legend>Categoria:</legend>
                        <div class="col-lg-12" style="margin: 7px 0; max-height:400px; overflow:auto;">
                            <select id="prod_cat_select" class="form-control" name="pessoas_id" required > <option>Nova...</option> </select>
                        </div>
                    </fieldset>
                    
                    <div id="prod_cat_alertas" class="label label-default col-lg-12 hide"></div>

                        <fieldset>
                            <div class="form-group col-lg-12">
                                <label>Nome*</label>
                                <input type="text" class="form-control" name="nome" id="prod_cat_nome" required />
                            </div>
                            <div class="form-group col-lg-12 text-right">
                                <input type="checkbox" class="" name="status" id="prod_cat_status" checked />
                                <label>Ativo</label>
                            </div>
                           
                        </fieldset>
                        
                    <!--</div>-->
                    <div class="col-lg-12 text-right" >
                        <button type="button" id="prod_cat_desfazer" class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Desfazer">
                            <i class="fa fa-undo "></i>
                        </button>
                        <button class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                            <i class="fa fa-check " style="color:#cc7a00"></i>
                        </button>
                    </div>
                    
                </div>

            </div>
        </form>
    </div>
</div>
