
<script type="text/javascript" src="/public/js/produtos/lancamentos.js"></script>

<div id="prod_janela" class="janela col-lg-push-2 col-lg-8" style="display: none" data-title="ProdLanc">
    <div class="divisao-janela">
        <form method="POST" action="" id="prod_form">
            <div class="modal-header">
                <button type="button" data-toggle="tooltip" data-placement="bottom" title="Fechar">
                    <i class="fa fa-close "></i>
                </button>
                <h4 class="modal-title"><i class="fa fa-shopping-cart "></i> Gerenciamento de Produtos</h4>
            </div>
            <div class="modal-body clearfix" style="padding-bottom: 5px;">
                
                <div id="prod_alertas" class="label label-default col-lg-12 hide"></div>

                <div class="col-lg-4">
                
                    <fieldset>
                        <legend>Fornecedores:</legend>
                        <div class="clearfix" style="margin: 7px 0;">
                            <div class="col-lg-12" >
                                <select id="prod_forn_select" class="form-control" name="fornecedor_id" required > <option>Selecione...</option> </select>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend class="clearfix" style="margin: 7px 0;">Produto: </legend>
                        <div class="form-group col-lg-6" >
                            <label>Marcas*</label>
                            <select id="prod_marca_select" class="form-control" name="marca_id" required > <option>Selecione...</option> </select>
                        </div>
                        <div class="form-group col-lg-6" >
                            <label>Cod. Auxiliar</label>
                            <input type="text" class="form-control" name="codigoauxiliar" id="prod_codauxiliar" />
                        </div>
                        <div class="form-group col-lg-6">
                            <label>Categorias*</label>
                            <select id="prod_categoria_select" class="form-control" name="categoria_id" required > <option>Selecione...</option> </select>
                        </div>
                        <div class="form-group col-lg-12">
                            <label>Descricao*</label>
                            <input type="text" class="form-control" name="descricao" id="prod_descricao" required />
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Quantidade*</label>
                            <input type="text" class="form-control" name="quantidade" id="prod_quantidade" required />
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Unidade*</label>
                            <select id="prod_unidade" class="form-control" name="unidade" required > 
                                <option value="">Selecione...</option> 
                                <option value="UNID">UNIDADE</option> 
                                <option value="METRO">METRO</option> 
                                <option value="JOGO">JOGO</option> 
                                <option value="CM">CENTIMETRO</option> 
                                <option value="LITRO">LITRO</option> 
                                <option value="BALDE">BALDE</option> 
                            </select>
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Espessura</label>
                            <input type="text" class="form-control" name="espessura" id="prod_espessura" />
                        </div>
                        <div class="form-group col-lg-6">
                            <label>P. custo*</label>
                            <input type="text" class="form-control" name="precocusto" id="prod_precocusto" data-mask="money" required  />
                        </div>
                        <div class="form-group col-lg-6">
                            <label>P. venda*</label>
                            <input type="text" class="form-control" name="precovenda" id="prod_precovenda" data-mask="money" required />
                        </div>
                        <div>
                            <div class="form-group col-lg-12">
                                <label>Observações</label>
                                <textarea id="prod_obs" name="obs" class="form-control" ></textarea>
                            </div>
                        </div>
                        <div class="form-group col-lg-12 text-right">
                            <input type="checkbox" name="status" id="prod_status" checked />
                            <label>Ativo</label>
                        </div>
                        
                        <input type="hidden" id="prod_id" />
                        
                    </fieldset>
                    
                    <div class="col-lg-12 text-right" >
                        <button type="button" id="prod_desfazer" class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Desfazer">
                            <i class="fa fa-undo"></i>
                        </button>
                        <button class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                            <i class="fa fa-check" style="color:#cc7a00"></i>
                        </button>
                    </div>
                    
                </div>
                <div class="col-lg-8">
                    <fieldset>
                        <legend>Produtos:</legend>
                        <div class="col-lg-12" style="margin: 7px 0; max-height:400px; overflow:auto;">
                            <table id="prod_tabela" class="table table-bordered table-condensed">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th class="col-lg-1">Marca</th>
                                        <th class="col-lg-1">Categoria</th>
                                        <th class="col-lg-2">Cod. Aux.</th>
                                        <th class="">Descrição</th>
                                        <th class="col-lg-1">Quant.</th>
                                        <th class="col-lg-1">Unid.</th>
                                        <th><i class="fa fa-edit"></i></th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>
</div>